### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by klaszlo8207** [psylinse/flutter_the_stream#5]
Unhandled Exception: SocketException: OS Error: Connection timed out, errno = 110, address = 10.0.2.2, port = 45864
E/flutter (22560): #0      IOClient.send (package:http/src/io_client.dart:33:24)

**Comment by jetaggart** [comment]
10.0.2.2 is a [convention on Android](https://developer.android.com/studio/run/emulator-networking) that allows you to connect to your host machine's localhost (to access the `backend`). Are you on Android and have the backend running? Also, you can try [ngrok](https://ngrok.com/) instead of 10.0.2.2.

**Comment by klaszlo8207** [comment]
Sorry I created a heroku url, thanks
